# Generated by Django 6.0.5 on 2026-05-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='oauth_provider',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nhà cung cấp OAuth'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='oauth_uid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID duy nhất OAuth'),
        ),
    ]
