# Generated by Django 6.0.5 on 2026-05-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_oauth_provider_customuser_oauth_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin hệ thống'), ('LEADER', 'Leader'), ('MEMBER', 'Người dùng thường')], default='MEMBER', max_length=20, verbose_name='Vai trò'),
        ),
    ]
