# Generated by Django 6.0.5 on 2026-05-28 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề tài liệu')),
                ('content', models.TextField(blank=True, default='', verbose_name='Nội dung văn bản (HTML)')),
                ('status', models.CharField(choices=[('DRAFT', 'Chưa hoàn thành'), ('DONE', 'Hoàn thành')], default='DRAFT', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Người sở hữu')),
            ],
            options={
                'verbose_name': 'Tài liệu',
                'verbose_name_plural': 'Danh sách tài liệu',
                'ordering': ['-updated_at'],
            },
        ),
    ]
