# Generated by Django 6.0.5 on 2026-05-28 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày tài liệu'),
        ),
    ]
