# Generated by Django 6.0.5 on 2026-05-31 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_document_doc_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên kho tri thức')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to=settings.AUTH_USER_MODEL, verbose_name='Người sở hữu')),
            ],
            options={
                'verbose_name': 'Kho tri thức',
                'verbose_name_plural': 'Các kho tri thức',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên tài liệu')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Tên file')),
                ('file_type', models.CharField(max_length=50, verbose_name='Loại tài liệu')),
                ('file_size', models.CharField(blank=True, default='', max_length=50, verbose_name='Kích thước file')),
                ('status', models.CharField(choices=[('indexing', 'Đang index'), ('active', 'Đã index'), ('error', 'Lỗi index')], default='indexing', max_length=20, verbose_name='Trạng thái')),
                ('content', models.TextField(blank=True, default='', verbose_name='Nội dung văn bản thô')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('kb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.knowledgebase', verbose_name='Kho tri thức')),
            ],
            options={
                'verbose_name': 'Tài liệu tri thức',
                'verbose_name_plural': 'Các tài liệu tri thức',
                'ordering': ['-created_at'],
            },
        ),
    ]
