# Generated by Django 6.0.5 on 2026-05-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_knowledgebase_knowledgedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ảnh đại diện'),
        ),
    ]
